### ISSUE TITLE
IPA Branding

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/rocky-logos#2]
The IPA assets are either the wrong color or haven't been changed. That's an oversight on my part. See images for examples:

![image](https://user-images.githubusercontent.com/22327045/108593878-5e435580-736e-11eb-8e60-4da9261ed2e6.png)

![image](https://user-images.githubusercontent.com/22327045/108593880-613e4600-736e-11eb-8431-eebefea295d9.png)

**Comment by nazunalika** [comment]
Sticking the overall grayscale thing that the IPA folks have going, these seemed to look ok (with the exception of top left corner asset on the menus). Just inverted the text white and called it a day... but that's my laziness. Open to testing potential changes/ideas!

![firefox_XmLU31d51z](https://user-images.githubusercontent.com/11469736/108676925-30f9c300-74a6-11eb-98c7-e78280696ef4.png)

modded assets below...

![login-screen-background](https://user-images.githubusercontent.com/11469736/108676837-14f62180-74a6-11eb-97a4-43d8f31fb529.jpg)

**Comment by hbjydev** [comment]
Actually I like that, personally.

**Comment by hbjydev** [comment]
Might want to change the background colour to something more bluey-green than brown, but other than that, this looks pretty okay

**Comment by hbjydev** [comment]
IPA assets are now part of the repo 📦
