### ISSUE TITLE
CentOS logos need replaced with Rocky logos

### ISSUE THREAD

**Issue by ewaldmire** [rocky-linux/rocky-logos#3]
Found these 3 logos appear to have been missed and are still CentOS logos:

- [x] https://github.com/rocky-linux/rocky-logos/blob/main/icons/hicolor/scalable/apps/fedora-logo-icon.svg
- [x] https://github.com/rocky-linux/rocky-logos/blob/main/icons/hicolor/scalable/apps/start-here.svg
- [x] https://github.com/rocky-linux/rocky-logos/blob/main/icons/hicolor/scalable/apps/xfce4_xicon1.svg

**Comment by hbjydev** [comment]
Thanks for reporting this, I've just sorted these out! :)

**Comment by ewaldmire** [comment]
Still appears to be an issue - I think perhaps you just put them in the wrong folder (up 1 directory from where the original versions are)?

Compare these two:

https://github.com/rocky-linux/rocky-logos/blob/main/icons/hicolor/scalable/start-here.svg
https://github.com/rocky-linux/rocky-logos/blob/main/icons/hicolor/scalable/apps/start-here.svg

**Comment by hbjydev** [comment]
Oh, yep, my bad

**Comment by hbjydev** [comment]
_Now_ it should be done, haha
